package com.example.annimation;

import java.io.*;

class WolfySer implements Serializable {
    transient static  int  w = 1250;// transient static has no effect
                                    // because the static variables are not part
                                    // of the object state (of the system)
    transient  String password = "KakaMaca";// just using transient to shield the var

    DogSer d = new DogSer();
}

public class DogSer {
    transient int i = 10;// instead of  i= 10 will be assigned  0
    PussySer p = new PussySer();

    int j = 100;
}
class PussySer implements Serializable{

    transient final int z = 50;// Since final makes the var to be just a value
                               // there will be no changes generated by transient,
                               // no impact
    int k = 27;

    public String catmi = "Miau";

}
class RatSer extends PussySer{
    String ratser = " Chits- Chits";
}


class DogDemo {

    public static void main(String[] args) throws Exception {

        DogSer d1 = new DogSer();
        PussySer p1 = new PussySer();
        WolfySer w1 = new WolfySer();
        RatSer r1 = new RatSer();
        FileOutputStream fos = new FileOutputStream("dog.txt");
        ObjectOutputStream ous = new ObjectOutputStream(fos);
        ous.writeObject(d1);
        ous.writeObject(p1);
        ous.writeObject(w1);
        ous.writeObject(r1);

// Deserialization in the same order as Serialization
        FileInputStream fis = new FileInputStream("dog.txt");
        ObjectInputStream ois = new ObjectInputStream(fis);
        DogSer d2 = (DogSer) ois.readObject();
        PussySer p2 = (PussySer) ois.readObject();
        WolfySer w2 = (WolfySer) ois.readObject();
        RatSer  r2 = (RatSer)ois.readObject();

        // If you do not know the order of  Serialization

//
//            Object o = ois.readObject();
//
//        {
//        if (o instanceof DogSer) {
//            DogSer d2 = (DogSer)o;
//            //perform DogSer specific functionality
//        } else if (o instanceof PussySer) {
//            PussySer p2 = (PussySer) o;
//            //perform PussySer functionality
//        } else if (o instanceof WolfySer) {
//            WolfySer w2 = (WolfySer) o;
//
//
//        }

//
//        System.out.println("this is DogSer i = :" + d2.i + " and this is DogSer j = :" + d2.j + "  PussySer p = :"
//                + p2.z + " And the pussycat says : " + p2.catmi +"\n\nPussySer k : "+ p2.k + "\nNo Woolfy? : "
//                + w2.w + " Password : " + w2.password);
        System.out.println("DogSer reference to PussySer  p.z :" + d2.p.z + "   p.k : " + d2.p.k);
        System.out.println("RatSer object ratser : " + r2.ratser);


    }
}

